name: ReviveRGosford
favicon: null
layout_spectrum: 0.17554834648035467
typography_spectrum: 0.009393379557877779
title: "Gosford's Classic Cocktail Bar"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#595959'
    - '#aaaaaa'
    - '#960606'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.960254275938496
purpose: []
